Repository cnpm/cnpmweb, pull requests merged in 2023-08, with the labels that each got.

#1 feat: ui enhance
  src/app/globals.css
  src/app/package/[[...slug]]/page.module.css
Labels: enhancement

#3 fix: sync btn copy
  src/components/Sync.tsx
  src/components/SyncAlert.tsx
Labels: bug

#5 feat: footer
  src/app/layout.tsx
  src/app/package/[[...slug]]/page.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/components/Footer.tsx
Labels: enhancement

#6 fix: error catch
  src/app/error.tsx
  src/app/package/[[...slug]]/home/index.tsx
  src/app/package/[[...slug]]/page.tsx
  src/initData/getNeedSync.ts
Labels: bug

#8 feat: dynamic code viewer
  src/app/package/[[...slug]]/deps/index.tsx
  src/app/package/[[...slug]]/files/index.tsx
  src/app/package/[[...slug]]/versions/index.tsx
  src/components/CodeViewer.tsx
  src/components/ContributorContent.tsx
  src/components/DynamicCodeViewer.tsx
  src/components/Footer.tsx
Labels: bug

#10 refactor: use page
  package.json
  src/app/layout.tsx
  src/app/package/[[...slug]]/page.tsx
  src/app/packages.tsx
  src/components/CodeViewer.tsx
  src/components/CustomTabs.tsx
  src/components/LandingSearch.tsx
  src/initData/getNeedSync.ts
  src/pages/500.tsx
  src/pages/favicon.ico
  src/pages/globals.css
  src/pages/index.tsx
  src/pages/package/[...slug]/index.tsx
  src/pages/package/[...slug]/page.module.css
  src/pages/page.module.css
  src/slugs/deps/index.tsx
  src/slugs/files/index.tsx
  src/slugs/home/home.module.css
  src/slugs/home/index.tsx
  src/slugs/versions/index.tsx
  src/slugs/versions/versions.module.css
Labels: enhancement

#11 feat: small data
  src/components/AdVPS.tsx
  src/components/AntdStyle.tsx
  src/pages/_document.tsx
  src/pages/package/[...slug]/index.tsx
  src/slugs/deps/index.tsx
  src/slugs/home/index.tsx
  src/slugs/versions/index.tsx
Labels: enhancement

#12 feat: redirect name
  src/components/AdVPS.tsx
  src/components/LinkContnet.tsx
  src/hooks/useManifest.ts
  src/middleware.ts
  src/pages/_document.tsx
  src/pages/globals.css
  src/pages/package/[...slug]/index.tsx
Labels: bug, enhancement

#18 chore: pipeline deploy
  .github/workflows/deploy.yml
  src/slugs/home/index.tsx
Labels: enhancement

#20 chore: flow
  .github/workflows/deploy.yml
Labels: bug

#19 fix: sourceLink incorrect
  src/components/SyncAlert.tsx
Labels: bug

#21 fix: code block highlight in dark mode
  src/components/ReadmeContent.module.css
  src/components/ReadmeContent.tsx
  src/components/dark.module.css
  src/components/light.module.css
  src/pages/package/[...slug]/index.tsx
Labels: bug, enhancement

#23 feat: landing page
  src/components/Header.tsx
  src/components/Introduce.tsx
  src/components/LandingSearch.tsx
  src/hooks/useRegistry.ts
  src/hooks/useTheme.ts
  src/middleware.ts
  src/pages/index.tsx
  src/pages/package/[...slug]/index.tsx
  src/pages/page.module.css
Labels: enhancement

#25 feat: overflow tags
  src/components/RecentVersion.tsx
  src/components/VersionTags.tsx
  src/slugs/versions/index.tsx
Labels: bug

#28 feat: files path hash state
  package.json
  src/components/CodeViewer.tsx
  src/components/FileTree/index.tsx
  src/hooks/useHighlightHash.ts
  src/hooks/usePathState.ts
  src/pages/package/[...slug]/index.tsx
  src/slugs/files/index.tsx
Labels: enhancement

#31 fix: scope pkg render
  src/components/SyncAlert.tsx
  src/pages/package/[...slug]/index.tsx
  src/slugs/deps/index.tsx
Labels: bug
