Repository cnpm/cnpmweb, pull requests merged in 2023-10, with the labels that each got.

#43 feat: hire
  src/components/AdHire.tsx
  src/pages/index.tsx
  src/pages/package/[...slug]/index.tsx
Labels: enhancement

#45 fix: ts
  next.config.js
  src/hooks/useSearch.ts
  src/pages/api/info.ts
  src/pages/api/spec.ts
Labels: bug

#47 refactor: use nginx & csr
  next.config.js
  src/components/SyncAlert.tsx
  src/hooks/useManifest.ts
  src/pages/api/spec.ts
  src/pages/package/[...slug]/index.tsx
  src/pages/packages.tsx
Labels: enhancement

#49 fix: 修复链接错误
  src/slugs/deps/index.tsx
Labels: bug

#50 feat: npa redirect
  package.json
  src/pages/[...npa]/index.tsx
Labels: enhancement

#51 chore: readme
  .github/workflows/deploy.yml
  README.md
  next.config.js
  src/components/AdBanner.tsx
  src/components/AdHire.tsx
  src/components/AdVPS.tsx
  src/components/CodeViewer.tsx
  src/components/ContributorContent.tsx
  src/components/CustomTabs.tsx
  src/components/DynamicCodeViewer.tsx
  src/components/FileTree/icon.tsx
  src/components/FileTree/index.tsx
  src/components/Footer.tsx
  src/components/Gravatar.tsx
  src/components/Introduce.tsx
  src/components/LinkContnet.tsx
  src/components/NPMVersionSelect.tsx
  src/components/PackageAvatar.tsx
  src/components/PackageCard.tsx
  src/components/PresetCard.tsx
  src/components/ReadmeContent.tsx
  src/components/RecentVersion.tsx
  src/components/SearchBox.module.css
  src/components/SearchBox.tsx
  src/components/SkeletonText.tsx
  src/components/Sync.tsx
  src/components/SyncAlert.tsx
  src/components/VersionTags.tsx
  src/components/dark.module.css
  src/components/light.module.css
  src/config.ts
  src/hooks/useFile.ts
  src/hooks/useManifest.ts
  src/hooks/useNamePlaceholder.ts
  src/hooks/useReadme.ts
  src/hooks/useRegistry.ts
  src/hooks/useSearch.ts
  src/hooks/useTheme.ts
  src/pages/500.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/package/[...slug]/index.tsx
  src/pages/packages.tsx
  src/slugs/deps/index.tsx
  src/slugs/files/index.tsx
  src/slugs/home/index.tsx
  src/slugs/versions/index.tsx
Labels: documentation
